[workspace]
resolver = "2"
members = ["crates/lexer", "crates/parser", "crates/interpreter", "crates/types"]

[profile]
release = { lto = true, codegen-units = 1, incremental = false }
bench = { codegen-units = 1, debug = true }
