[workspace]
resolver = "2"
members = ["lexer", "parser", "interpreter", "types"]

[profile]
release = { lto = true, codegen-units = 1, incremental = false }
bench = { codegen-units = 1, debug = true }
