[package]
name = "parser"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
lexer = { path = "../lexer/" }
types = { path = "../types/" }

# Small container optimizations
smol_str = { version = "0.3.2" }
smallvec = "1.13.2"
