[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
lexer = { path = "../lexer/", version = "0.1.0" }
parser = { path = "../parser/", version = "0.1.0" }
smol_str = { version = "0.3.2" }
