[package]
name = "orion_parser"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
orion_lexer = { path = "../orion_lexer/" }
orion_types = { path = "../orion_types/" }

# Small container optimizations
smol_str = { version = "0.3.2" }
smallvec = "1.13.2"
